### ISSUE TITLE
SFOS 4.0.1 libcontactcache-qt5.so undefined symbol

### ISSUE THREAD

**Issue by pmastal** [dpurgin/harbour-callrecorder#65]
In the SailfishOS 4.0.1 is the error:

nemo@nemo ~]$ harbour-callrecorder
harbour-callrecorder: symbol lookup error: /usr/share/harbour-callrecorder/lib/libcontactcache-qt5.so: undefined symbol: _ZNK10QtContacts21QContactManagerEngine13relationshipsERK7QStringRKNS_8QContactENS_20QContactRelationship4RoleEPNS_15QContactManager5ErrorE, version Qt_5

Can you fix this problem. The app is the best.

**Comment by dpurgin** [comment]
Thanks, I'll look into it once the 4.0 SDK is out. But the best I can do is to repackage the app without the built-in system libraries and hope it works, since I neither use SFOS nor have a SFOS device to test. 

I put the libraries libcontacts, libcontactcache etc in the package to try to get the app into the Jolla Store because of the dependency requirements back in the days, but I think I'd better remove these for good.

**Comment by pmastal** [comment]
Very sad you don't have SFOS device. Installing app, the recording demon works and files are created. Only the GUI does not start.

**Comment by dpurgin** [comment]
I've repackaged the application without the built-in libraries, and the UI is running now in the emulator. Can you please check if it works for you? You can get the updated version [here](http://dpurgin.github.io/) or on [openrepos](https://openrepos.net/content/dpurgin/call-recorder)

**Comment by pmastal** [comment]
Now GUI works. Side effect - matching the data from the address book does not work but this is not the most important issue.
