### ISSUE TITLE
Allow user decide whether save or delete last call

### ISSUE THREAD

**Issue by dpurgin** [dpurgin/harbour-callrecorder#9]
As proposed by HtheB on TMO:

> Can we have an option that it asks before saving after each phone call?
> So if you press no, it will delete file, otherwise it will save it. (So if somehow the message dissapairs,
> it will still save the recording)

**Comment by robinchew** [comment]
As someone who always want to save everything, I don't want to accidentally hit "Don't Save". So perhaps, place it in the pulley menu as the second option or something. Second option, because even the first option can be pulled on accidentally quite easily. Maybe don't use the pulley menu, maybe a dropdown menu, or maybe that deletion bar that counts down when trying to delete image in gallery. Would love to have a discussion on it.

**Comment by HtheB** [comment]
@robinchew
That is why I said the 'option' to have it. So you can change it in the settings to 'save all recordings' or 'ask before saving'.
So both parties will be happy ;)

**Comment by robinchew** [comment]
Then awesome. Carry on. :)

**Comment by dpurgin** [comment]
In addition to what @HtheB posted, I'd like to try and make it in the same manner as network connection popup. Since UI application doesn't need to be run for call recorder to work, it can be a feasible way to perform selection. It needs checking, whether this popup can be used and that it cannot be closed accidentally.

**Comment by dpurgin** [comment]
TemeV proposed on TMO:

> Remorse timer would be cool way to implement deleting files after phone call.

I'm not sure if remorse can be used without host QML app

**Comment by dpurgin** [comment]
Implemented for version 0.6
